apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: blackboards-election-admins
  namespace: default
spec:
  encryptedData:
    ELECTION_ADMINS: AgA+S94WyF6MLi9QOfpS+YD3NnVdsQjtWlve6/ApF5kXgMGgu0Qy/n/ZjE6F84LjEXZA5lKbNaxJ7ua/2JKF/ghwow21xdngcRJA0rcwalhxd83BGDeYO0CM6VpeY12a0o7+AH5l3wun5jGaoFX84+VHZAqIygxb7TizJdxYRrUWET43YQhNVb4Nv95zl73DbRim4VX/ki86yNgsGGwrVb88CNcWcB54Ch0lZHcvdexFWjnOZsplcfDUeYN63eKflrn52891yjce9HiLqO/rJ8po65799wPPWZv9egIyXlEljw/PeU4KzagRZsQbz2Q3ezaQLp44CIVGFi4TkQcgyKU28CHv8cwL7rKtLA7a7VDuou+kOXi5AigyprWM41BGaFgrt+bgJIUlYY0sTPa0qhtYk1J32uIGJTJFfKHRGyrX8B3y0duTOqOsSDQx2qDQDCFtJEeDpASFjVHXj4u7c3mYCAl0IQWRCvw9z84bHCMpebNTFzQS3G2p2k2o6Jl4NNOIc2P4raxJIHTSxlpm4U/d5d7dyaowx+G6keWEgJslci1zEdqKt6Jt0SpttK+GF6TtXfJR8tXoQ57ER3oMHRHQEeapwkQbUg9FzHzT6+Kq5a2nAxLzEY0l+c3bM2+VXDqvsvlWtR4SMq037fj3GVY8uNNCbhuIeRCmKWGalJU2SMur/EgVnLLDZ2z8wlRgqAp+Fw4jeiMK2/+iJNd2GJU7t2RFANxVKg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: blackboards-election-admins
      namespace: default

