apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: blackboards-consumer-key
  namespace: default
spec:
  encryptedData:
    CONSUMER_KEY: AgBJ0p8p6bBN4Rp4WGOPb/kIMZ+UgZt+xqDLSg1R6vDWmbzkLCrKC0jPqb87o4iKIacPBIl7UrDPuCnY8Z0uVYuXMXDNrK07Z9LSccEnMBHswHV46z9tN3RhLjg3yYHPUzD4qPu40cn9Hyi99PI5NWfFihDoCwsKXZNCM+m0aBS7cRshhAZLnAsr0cXLqmH5ehQQBk8EtO/MRSaIOqsSAqQu9U3Ln9M4XURbF3rV6/W7BQSlAqdnQovhTCAZ0rDbzhm/LDD14oQXiw6dgNeLgDIiDJmVdqprQHXFdF62QcbG1NZi2xjaF7UV+1o+yOeXn2SteoQHkaC3K7q+rt7EJxQ8HD5l6TTmgP2VIlSLZTj5SMvtsdiHj8xAIodrlY9vcQIhadnvYcE+qKT6LyPk4WxFLvpCMhjytz/gD4SEK+1e7RiuAteLHqTOjxIVySUYu8Bwqai/5BQpH87bwTpbmODAJnImT1Yw2EBFS7e5NKqLJN6g8Aj0Z9TjcgGZjqvGHMZYeIvr2r1Cv19/4yNgrrYrUk8ITK6A24OTPR+1CR3Sh66s5P5GT6sQ8YwAvH7Mi3Dj2QVtHUmqXcMvVlXYYEW7DHNdfD/PqHHrvr9ZwOqSFX1k0NfUZ0MgnKrkpTrvgvOMlPRNWG73F3OZULLFi4ShoI9PY3pm0C+RFVOK8bj+rSqndu14ulB2OlZnHitiZGnA6flBVBiQ7XRoWXXaug==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: blackboards-consumer-key
      namespace: default

