apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: pythia-deployment
  labels:
    app: pythia
spec:
  selector:
    matchLabels:
      app: pythia
  template:
    metadata:
      labels:
        app: pythia
    spec:
      containers:
        - name: pythia
          image: alexanderjackson/pythia:20211225-1231 # {"$imagepolicy": "flux-system:pythia"}
          env:
            - name: token
              valueFrom:
                secretKeyRef:
                  name: pythia-discord-token
                  key: token
