alb:
  addr: 0.0.0.0
  port: 443
  reconciliation: /reconcile
  tls:
    domains:
      opentracker.app:
        cert_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/opentracker.app/fullchain.pem
        key_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/opentracker.app/privkey.pem
      tags.opentracker.app:
        cert_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/tags.opentracker.app/fullchain.pem
        key_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/tags.opentracker.app/privkey.pem

secrets:
  private_key:
    location: s3
    bucket: configuration-68f6c7
    key: f2/private.key

services:
  frontend:
    image: alexanderjackson/opentracker-frontend
    tag: 20231026-0553
    port: 80
    replicas: 1
    host: opentracker.app

  backend:
    image: alexanderjackson/opentracker-backend
    tag: 20231129-0813
    port: 3025
    replicas: 1
    host: opentracker.app
    path_prefix: /api
    environment:
      DATABASE_HOST: "64.227.33.121"
      DATABASE_NAME: opentracker
      DATABASE_USER: postgres
      DATABASE_PASSWORD: secret:j9VBUWVGrsNDDGBUAwdSIdnxviUrHjBowc3ze+whOrg9nLY6a/GjVYTnWW8QYeIdGsP9X2o4Ns12+THcpZserHqvLkaBEZUFy83x238WfV7NKhMAMQonD9N/VIZX9r5ukBFK6g37dnu1UJK9ttf3MGHkZ7s36sogR9Q50J9OX5NjVKIlV4EZh5/KSTHxJLFWCk7Fuu0Bxqer7PL4s8ZGKjTFVYNMZDxhc4D7qNf3JnQHejyHc8RjJ2A/ggsMknbVUHruGejsF45aLmvhjJvpVs2XlFmeQ92e9cjY/11ORGN+L7IMoM8RH5txuJF1gp49ExPVAhidt0dX6BGnndt3Uw==
      JWT_KEY: secret:aj2H/HfbWsg9/8LZcmFIkMZEmDJqsBzS5Rz+t22dY4AnEKwm3hhBRwGrFtX6VBVmVHiuRKJgTrctEsF90eXc7keJ/ozfHqe5WReLmM/lRyr/YGnPZ4uy6g34o0EufP+w9hJSivtxNto/n14NkmLVj1GOkt9CdhxaJAXiHtzXnaDq0VUVP/Iv1c2R8i93vjHx3prYdoPRUuyIg5CvQJe715OqVvqFDzdFZXGkx+wV2pE4/voiDTcCRnzORWzQIe1zy3vntp+0ZKwbinDUCISaOqgxZo3KairWz/a9A5WZMYCnh5ltR0cj75FouvETEKpwt72KreJnuOdjBV/s9ZtFjw==

  tag-updater:
    image: alexanderjackson/tag-updater
    tag: 20231108-2014
    port: 4025
    replicas: 1
    host: tags.opentracker.app
    environment:
      PASSPHRASE: secret:mgVl9nw3UsAI7Kw5U7g0iAmba9YeW3Ly9i+FvJpR9EFbnfzo1EOXGBqPBVo8qhPtHjb6iW1zOqOba4y+cFj7luoRy7JQZHAu8OeJEJyRadJJQgZH3TKJtLWjM5YOtwTOmPhv9NF3FAnAqaSAelsBAu4HLVg7iR9CavLfcGUcu4t9eQtmVcaQC1jgJpJP6luy3z0NOkkoG+SCzGBIwYQGqAsGvhYqi9A49GgErUdzZjaAIb8VK8hQMOPXxQ2k7pPfe/VipkTmd2vGkdVhrU6PGBkYIwxBh6IbxajRgyau7hi7vekau/xE30VoklP/t9GpmMBJSOA6mKgFly/G8vxw7g==
      GIT_CLONE_PRIVATE_KEY: s3://configuration-68f6c7/tag-updater/id_rsa

  stock-notifier:
    image: alexanderjackson/stock-notifier
    tag: 20231110-1014
    port: 4025
    replicas: 1
    host: stocks.opentracker.app
    environment:
      PRODUCTS: secret:PnbCf9QczRmbqAnzIUizfP2Sf7nFIouHiOwHEnmLcIEabjdhaN7l2YS5+u3DyDqX56W8i0x2oXK6RnYRLIhCpLDiYfpm09EzBI4TwM6z0Q3eMYDH/1yVhfNt1QYBsfe/ECrkIm3N2ivq6fuvTM0bVtryA/olgndYblmxZRoDhsnilC5QGKtYUQwPrvrz8DhZr4jwBs2FvS+K9U1fqcxYGP69an7d8ijL1LtU4RXQ4ZOnFo/NuvtTJx7kUNPDlsT5QcZhDNt4GTX6Mxt5Ak85A0QuYsAbGkLnFy4hnks6go+l9bXuprBN4BaAPvM+2JZNItchyiEipsgLhewv6Achyw==
      DISCORD_TOKEN: secret:bfXWASQyzM8C6c6TG4CHIibsXWFHw36yDmhrJNA8ywFFrxBw0i8nIp4bVWSrVwjBU7zORhd+buVpBv1gkBfytXgQfw23DC5HM5CWhRXP04qRjhcdAjj2/9jTG2WPpEj15bWvf47H9BaeWOfI2qpJC9Yiex8bnGMB3uJtcSVF65TwuD9nMrNEQVRSYeNUZ7DPT0qJhcz8LuoprAgn6JON8vwE0hOsmwM5irm7ZXwVIoAnkKgwZfPnklfr2k/lW8aH7FRH4hLLeMM5Kawz9diWQf438TqkJ8V3KmAiofaZGoipUZG0tGsN25FtB0J9Wjz/Un8f0ubgiXLrfbo1g71H1w==
      CHANNEL_ID: secret:XluGGnI3gxRnZqXh629wlnu2RcEokw7Iv2yjrL9QymFnfTAsVp6Eh6+4VSAUmfesaykZAit5Q+KMaElUA5N4YZHNW3FoIDhRYR7vJyIV6t/eCyMnNYAcbCSxEeTohZWnb4nlwW7wJgtP+PpVzJ0ueeIBNO3zz0gbirFrjdCTvbsdtahlXXmd6XYpeehiDJsNGliC/+aqFzTmn+KobHRcFWQIQ4icaltw7E5sSoCymzDRM+f+0vbuXze2WRH04auGcMSv4YQgyPBBJZn4Ai3Fv8UwwleTGm+Et3hFON82LvT1aUYH2+YO89f660sU9Av4Z+r2PTkZR1H2O37mjZzNww==
