apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: postgres-persistent-volume
  labels:
    app: postgres
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: "/var/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - personal
