apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: postgres-service
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
