apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opentracker-database-url
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgB/7QYvFSTc2EOxktEcSy3I2U1kJuumRdjv3dkeXHu4EdoCsyQzBbRntpT7ugyfQiuG4aEMHu2g7oKn6tnkooDBCJXZcbiGAq0a3w5Md7fQbXdwHJklkX4x7APeIKvjTeKGaWgPi/7z8AulWsfxuOAF1MNFaqcF8XJ3RIrDJP1qFWr/i7vEzjyRpnwsTt7S/1aGXgHK9tmIg2E1TQYPJPAgIutIHbDzYOwUACmGMgqecLdP3hxvZhqF4sE+GMOXkoy1xCFX7aKOcHCx0rIaWgkgBPVfDY9oeJ6YV3yC9Kmhy160eCTkLf9N5AVi1QQaqVfhHOFDW/NgJ1tM2/m86sriHf2qsskQIq6amsH+qxbpO7PvE0VZy7cFbV9IcoLTyzUVsiwioWNIR1B2S2Y4llNaAM0Q01e8JfgMda7zIoj2OnBB4EIpmRw941+oWVPMOjsERV5O0wgazQGIDSo2sa4EaQPxsauy00+UzeJMsSKaO6oDUiUfuwm85CDcUJrFNZkpIP372UE1lRiudIJOKIk8VpnJYH/1T/K+iAaby7gcqFWuQktSB1Mu+IA1X7z1rGb1dMHF7LjX6Nyj3f/3WNb5quSGguAg2WeGenWhfLDzqBcu7s6NMr7Qfesw5OLKaPaKdTl4m5VKMR24jUfBe/s3zpZfKAEIKGF9SsYqnZtW9dJZdbLlLOQQ1G8vtGtzAolxR0BE3DfWBET0huoKpJdfnpq46Lo2YNl85KbEnK3AJtYENDHtKqvVN4IZWV9Gtox7MNMh1WWh65/v6j1ze6fbnKhbz0MPbkFWd3yVu/WQeSb76LCsyy/oz4Nvj7YhrdcM7+GqLA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: opentracker-database-url
      namespace: default

