apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pl-tracker-database-url
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgAgQKlmDnR45icUHqDa1VW0iI56NnWayc8CLoyMex5YitomjQOon4clufSDSbDm199dqnxvDS3fxMGoWK3Lqo0L4BxDWFR5haS78Hlj8RLNAmSjZvLjC1/JGbuvFPMwNcUxW3Cj9SsdgHfpfYyPH7v/NLzVNQ75lSPBmRBjMjcR1Ag+vPs+jCymjkWkG8M6vT2gNH132kasYIdO0475mHW+BjhLoADMbT08M2YfA5d61yN5RskUQ+xl0hFKpqrd1kJk6LYJk73B+b9+gR9+xmdqTUMVANOguKs3KKraCIlXFluwc6T2k6qnsiL1sSEd9fM03gSEauUWm2AE01+O9cgkS2RRYwD9UnxryzdyW594xJGejlrfHP11o2sE2za8imO+F5XL/WSJictL0WlMJXDo2OeTVJuYSJP8AMjqBTjxacveuX80ILzF2CkVs2imJBNKGg/bTeO3V+xax/NCyp3xwEeHp/t9GaZa6t3noxCijFoxAc6FHev9vYeoruJduHLLEYExc7VPBwyiS6oDcO7QrlCsrP/HkKirTe4YPNRqy+x27McwIAUnTgpGxFZS4AsqCodSQ7ecX5AFuHiVfFQgs41bMAXvMUJa30qJslH3Jw585xHoY3k5PsbJ+F+wa6txgs5E3O0ueOMQeQaMcFNhdGmJ+N0GlTnS7qvElNPiCHnI6fHWaEjUfJyaVbyoQlRoqiUOeKYCa1GG+q46H+pdRNlUrhVGFS4WvR/cJB7js5COD4I932uzzi8FgEzK6QaPV9htXAaVyNj9APOu6QKHypOrEuTAu4Kmv5FS/8EbzXtWACYtiDCUWB9hxmUVM+niRAPwZg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pl-tracker-database-url
      namespace: default

