apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: default
spec:
  encryptedData:
    PGPASSWORD: AgA285+fmLv4XDo8yaX0P9H0hyR9cILCw97fkgJEyafbKnFIo7hjvfZwr7FQ94Ua+3ty7fYlC8HkxmBfG/+YPZYi4E9h73sSYzcLaYV8vthSHcgbI6h7I+pe2veC4CQ9b76BcSDFPJK5Ig9EPe1jPlMB0o4c0pjVBR0kJKShhhF1UbyYpdJ294oZYYf283bSJFWGQad7ewq/53ixZ5WFU0okrYwu1NVU74DCZ/H9rUahGksRx3V06AUBx5SoHW/fc8O1MhuJC5H9JVN02/z2cInTYzW4JgSU0oYU7S3q5fQyPkSO/kS+cKueT7oDm3At5j9MclMlOqvnXkj/Yv3MAgKqqSJRipxhQrVvalhG6KD/2QCmZ/YPK0pnCpn8zm8pEoZ6aR9YtiUThcY32yVyM2e4w5lV1AAmeriW6oWzHyw7AcYm0WQlZwrv4wJCvEo4Iiy5hTi/5GMWRAldxIFmv0B633c8Y1V2rKa7pD/Dms1EQZA0XmSwcXYqgZBgbyXVl7shIGy5Nb3mTkOeTja1D5OTARtgn71tjDRcACm8Qs49WeCwA4/wiygsfz6ecZHbViTo8f2XhFsN0vGMGvmJz+AAw4WaCfvz7EY5Glq552QxlSgrHHjpZNJzGKdbIEwWct+jKrEqh1E0wfn8XtwB+hsG0RBfjGDSOdRla7sRgg+Fulo/Vr3v8Q/luI+TGjJoGNg+IeTzqTlA96yr/4oVXL3ItdiXG6wz/+q4rW65tA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: default

