apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-root-password
  namespace: default
spec:
  encryptedData:
    PGROOTPASSWORD: AgBO7hi3SmXlX5u6gds33UODuTeNCmV4m4Q4ht40S9eBAlmjaoP3Gkc0BeS66qtDgyIxodcWbC9Ms1YKvj1ewx4iPQEx/OZb4Fd6Eyq6D+UDyYyj4cTdTjfJjAS3WMascBCVA3Lyq+gbx+mTbIO32CC/JIq5ij0imVf2LBTk7j6nBfpAUG23Uy2n1ladVvy60uRIckRN3Ng0MFQqGDe/1iCc0/jLeXqnZZc8g+X3Ne7jvtGCEMmfYfHTsbHNeSLvNV2GPvMURk1JoCsXIKjGzsjYDk8ZklKc9Tg13Amlq+HUp/SeI+t8VIQ6zmcqTVS6bv940E/L0aHM+j/CJxPYRTlxxz+o13pFG3BlW6k4QqBXCSkcltyCQqE4+DFpQJ96rkNLsWR8DhOjLAn4ds6Og9zvLQCOdURsOAmEkzqVElEoVV6v42gdbzO/9AoXve3Cg7tLG7pWdYklQR62To6y8BwvebhrapVXbY0t6Xm4XZccz8PkMwGvVILR2oWpSBOfX+y92RhdKJ15XeioPPUGFGFPtxBGFfvK0IcXA2aFCLs3BwL5Og2msukYTGYdJxFSabw5XROIJGGN/vzuozvopVLVX4eU+JPLodUc0WAq4n50Np3h7VEwlnk4Tp2+wtVmv+LvT9fhqTiIJFeFh4F+ymHbGL+s5YAktqfAQ8ROkVL2HDOW5dBtaLxO8EpkVmF/So3XWsfdTDVxycaAW0fnhuhinVTx2EueKYoY5L0GqytcRcg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-root-password
      namespace: default

