apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-host
  namespace: default
spec:
  encryptedData:
    PGHOST: AgA6Yx/sLyNAaoAN8Qwwju1bqvSP2AP4FEQYJ7HpLLHg1PL5fR0t6eI6LdjEox1m3PRFNXrSa0GoASG0PDmqQU1R9PwQ03/iiIJhBUzt/77GMxNO8/s6o7P7339RuJBknlVTMj2UhQJ7fRBM/91EA/nD+96GAfz+AcZ2+gsGiRhgD098EK+6e6rX8cnXMgBFd2ynieb1guHDjwbPCIxnK9TByBcE28+573xr8k9bjAiRN+Lo6y6oGoaH8YhTJXscuBhsW35+ujzH7TgTj6f/M4gQWStWsE0kB9y7otymiRnGlGv+678I5zyitcVZosNGEYJdpKUikb50fWPcuSWGQ9TeorQW6Hsp80ms5AsmgLpO6WOwkwQE0E+4KqMviBMXKCj5g8s36OoMI4/+bNNtcfFOP+BD3pOiyBzP2wvV+xH5lTIwQNWhhjnTwXAOcBjyPM07tJGdErBZPV9ncLbCGeHQZuKqjo0F5/erAQfnbcac3xh2RpVF99mE1Ks4J1RuTA6mr3wRnkN7M90M/xvDx9iVBiPl6AZ35WekCF9X41FavPQvyp405W5BhJr0EMwVBjzuu1CceOw2nNsyZ89KiyH6EQXJUiPozwVmcpqROAf06z7tvNaXQDXdXcGmtY/qQElvRcg+0gwab2oLvgSgEnbD6f+nhnvg1ETqgNOeoGW96YTD4bI5Q6gFmIzp4ggyf+4K6+hVD6yAq3eJ5Yc7hj0OBG46dMJFb/hNn+64KB5yEQTtzRhurgTgMWY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-host
      namespace: default

