apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-user
  namespace: default
spec:
  encryptedData:
    PGUSER: AgB9IfBLKwmSBDilhGVQ0ufb2N5W4evOFRNX7ezT47Fz00ZPdFukh7S+aQzz4HE9L5XQ6Nyubd9AzJHAWa5X87+G0UenJrOPqBGGxwmNj9WC4YYuyzlBz7KS3Z919UXLd9Xr6nG8qjB5+R4eYqiKnFWdCXKZSbf/ZnDOq0AkunxHyN+dIgJbOx5X8ivIhuuwZOIJXd3qKsf/SOhKo8S9ILdfhKpEUVBHpZpvt/29AYkSyZ3DmEq7FI+mIr5Iyw7zq7Wuv2bSMpR0NECUxKm5jR6muDvoYPzx+yYQDCDNZsU7MjVf+v7Ygcj7/FNyqz1JayGFo/RrGggqHU0e8E6wjQsaiD/jPOOYFuYtlgtAU74SkB485PPcN+bRYz60ApcFHteiOdTjrlDm679WGsqPAppJhG14iBxvevuEuC1Z+cEKBMLh1jYJ0PpUf+cGJNN5u4A6n4jDtMK3aj+3h1BVAOU8tsdqQM5K8aLQtOGwaG5vVa9ER6E1qDN2LYgzlC9wn7G+f+rytremc1dkxzdANz4/uehw/tvDNqgI67hrEySJicluXq4ikVrkXuBOl9+3ebeb96E4SCqVv3ABCFM30hJIahTi3lvQhFjcpnGbaaHKQyTGLoLQ9mmB7ImmuWjuB/vpMAlcdA0Qt0uMUiKOsvPHmMZNtAOO830alB//86c4nRWR4/15m/0N8CowVU/iS9bm7YTDy3zBq5xlMr/3a7dSqB+t+w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-user
      namespace: default

