apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-database
  namespace: default
spec:
  encryptedData:
    PGDATABASE: AgCDfaoHWcCc8gnosE52A4b2ztIm5NzQatfGdOdr2GAoBEiV0nHun6bgxZOUBGCjiBLdketoaUOxj43z6nWbIJTfweaGeECjKgHWhvicGGJGkqsEfEWy6Xe8G/dluw8JHEJ9fzdzHEIt7uRGuIo/vxrx8cahNFBxpR6ZG9ecgpuu/UBwOqsNzHf2B4BieDCC/9cEeKIwNa6It8OMBq1SKdBRvofUrtyyRfCNIxGw+CQQFmzYTe7KSm4menhjhLJ7h8FSZI6KOYI5BN+wAO5r5nBtUm974sT5p2OPJ1OF3qLS4PG6SkNuSllOaBMouNd/htP7+slHUr9qTwXkAF6QZHtK25fZBx5Faq6EhaH9WgoPfu0V9KocfGYsfvc7OrFUxp0+TM+8W9hmNVQAD8DNQrSTAhIEKcIFSfKLYXFnfZiNOQ9Vll0qE5XK0MjvNe97p1je0cKxIJnBQPFhdQqVi3tUZ084SizxJSIQ17VLRDs6t4z9wbSVF2aCPSXhV11wD1adoPCV71QfNBKlEaAwWHKuy8qp7Gro9rUrI0maJAgmXmZ2Vn706VSWpiPEYNFGr9tqAJHb0nk2h3F8RN45Gno5dyQMy35+t/nNv2Xg1fjFxeRU8dA+X2iqmxVzw65YdDoYnsI+/ZX6Sqtop/Oif1kHxY5RTXF7kNstv9zw6JPLet8/vIG3WI3NlyM2F9fnZBuxVdbcNfhk21H7hogT/FS4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-database
      namespace: default

