apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-token
  namespace: default
spec:
  encryptedData:
    DISCORD_TOKEN: AgACpSBjNJp4prfan0TsldACus3u2CpUWUUtpryc5Hlw7FEaid7O5p0e81QOiqnZmP1ioyLoPZvSmEcC+KplaIXjmlS9dZ3nYNvh16uyUCgKa2RnbBS2D4Kb9ZOFc0Gd8YYoex+oIlGl1+7HGeYEQvqhnRS7PdoE31M19xfa9VLdhbSFo4zDGRSnkuxSafvi759VnOters3WBOMnIfOxI0QOLA4CkP6mgc2UCFEUMwDhiySW+YKwnWnsK6Ako7PJCLUtDe+bmU2meC0vqcuob6tRC040R32i9nQ1bbCUjZpswp8VRrS46DfgLeFWwJgclmbBoyuHCjYZOF5mj7fawrEUfWnkbsg+DCKnLcgnJSZ9fcosG7HUbi0Q7V21DCVNPhtXBdXogh3YWyegkkMBkPBVgtzkLyvFEKRieUwy6/ITvLOzQcfn1c0Ftf2B8DcJVebvHzwPP2GQqxhK5NB1ucBTAZoAQbY3WTZ+saaX2rKwu2roYr1JpPIQz1BuPFv/wpYotFZ3/dH0MuYbELDYomF0HyOvKCSMFYoZLOWl0e2Mx8ocemmuOWvroijaa4FtLkjKkjuEkDxWfMUpwrXUaoh7L86JfjSGSLq2Qej7XaNBdZHQbcNVr9loSg6PM9WLo7rYCApXIZgZxqDQHalE+3N3L7HQAL2LEsC4dRq1zyCkX/xWewmZQ5ag52L9uMjd2N6cf7S/Ggt1EVHCpYzhdG7TjUzBS/ULQF1FJifRPLNrC4kVsanWmaFGwJDB/TSY3RVjat4e6EhZviEVZw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: discord-token
      namespace: default

