apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-root-database
  namespace: default
spec:
  encryptedData:
    PGROOTDATABASE: AgCDKOaWd3zLsOfLjxo2268Ysc3UBCNwiB8pux2JAJRGOpnz0NwNSafAUVSrnmianul7dcauNoEL+vL6ukucGmyAxXhWGN5WnAOcE2Krv7tcdax0tx+RD31GoiQvc5y5qHSsyuQyefSSxRKr/Q34o4VhZuLlA/cTPzGDKFKFXQ/92aFb4rE1cFcnv1yPpwZ/IUVpELYVMdeuUN7Mini/aQ7RVihNc9RficevrHPKDIcDVLmfgCLQbE+rV7YM+9Bdb1PuhaAwqFivvtXsWgfO3RVJrRxez5Di08jxSAm/BNNFz4eIti2oJKpRd9lUsbWPSyLJXOEmVFTbfnx26UD15gCRBs1QQiSG0tGCcwBW/ywMZNorpBUhaxhHIX1O4tl3fL+zEZgu9QILubkIrUMKkrYQR/OjsK3AjIx5qJlGrJDS10ukkGZstCWHjcOTgHreGzwGIfFQ+zvhkzJJKXvpb4ejs4LM7oDfXab0yB6usOxswCwklQzSPlHrvSVR4szHdcBI1UedeSwaG3tbf6bhLUdByxHjmB5KAj1Oai8449PvOWOCXeS67TQIGALK7ceE1S5O4oY4WWKIZrOyaUBjRa45D9lsBwzwWEmZdF2/fyIM722yospJGMZDk1xVQBXMV527huV/zP0Fsx4+ChiyGnQfJUPBAgfTv5nxrmv54j1v3Nx7zlAx1tns+U3ov+hz7iTZB9AxZfwTng==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-root-database
      namespace: default

