apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '1.1.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
      interval: 1m
