apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: blackboards-deployment
  labels:
    app: blackboards
spec:
  selector:
    matchLabels:
      app: blackboards
  template:
    metadata:
      labels:
        app: blackboards
    spec:
      containers:
        - name: blackboards
          image: alexanderjackson/blackboards:20220107-1445
          env:
            - name: ROCKET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: blackboards-rocket-secret-key
                  key: ROCKET_SECRET_KEY

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: blackboards-database-url
                  key: DATABASE_URL

            - name: FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: blackboards-email-from-address
                  key: FROM_ADDRESS

            - name: FROM_NAME
              valueFrom:
                secretKeyRef:
                  name: blackboards-email-from-name
                  key: FROM_NAME

            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blackboards-email-app-password
                  key: APP_PASSWORD

            - name: SEND_EMAILS
              value: "true"

            - name: CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: blackboards-consumer-key
                  key: CONSUMER_KEY

            - name: CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: blackboards-consumer-secret
                  key: CONSUMER_SECRET

            - name: ELECTION_ADMINS
              valueFrom:
                secretKeyRef:
                  name: blackboards-election-admins
                  key: ELECTION_ADMINS

            - name: BARBELL_MEMBERS
              valueFrom:
                secretKeyRef:
                  name: blackboards-barbell-members
                  key: BARBELL_MEMBERS

            - name: PRESIDENT_ID
              valueFrom:
                secretKeyRef:
                  name: blackboards-president-identifier
                  key: PRESIDENT_ID

            - name: SITE_ADMINS
              valueFrom:
                secretKeyRef:
                  name: blackboards-site-admins
                  key: SITE_ADMINS

            - name: ROCKET_ADDRESS
              value: "0.0.0.0"
