apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: default
spec:
  encryptedData:
    password: AgC00ZJMCByRl3H8sAN2GN4Eclu0Gi5nY+gf2mDO+Fhi/sY9Qv+iU2TTRWLLReIqtTwAe3PN9zOlM2OEEhP6U7OZw3DZbZDqu9U7dFJT9/RCH1GNGll7eeolV3kyIf7Bz99a8jHaLdJS5GMjXx8wwbRcqpMM3wEJLcXctSTOmL1pAqT2IonqYOMN4S80bvGEfVXf8fZ3FvF03P9MQ9lPH9nK0F5MvWxJNVaIp4pOV6P/SL8xlSJJmcBgPFq4AyO2MbqZUJrA74MXgOL0Wwbbm7IXP5HxZZpUvaL4/wOCdXlfB5s8mflMAftcVe/xKlw2AFV0fDYGl83AtncjPBjkyCvH7G32RkdcPtojKq5Yb+RG89hfJBKCfpE8J3SA7xV0/qIpbFKHVHXBD3KayJnwSx4lxDJX/UrAcSvg2kdJmNPRupOPAt7mFDFnxGc3fR1vauRVErf7vshS7aWFVK+IRvM1UQzJ64jhUKVQQzMh4hjMgrQbR+fcANOUE3QQQcPk8NpNBxBuAxY8lozuMS6zFOVd0BJjO1J037EN8MKtL17cH3fYLo6i4ngUkx1RxnlOm2+MP4CwpO+JZJs+mQqKW7G+bAHIQKdbvL5K8hhjtxxuJexa1Uw1+0X9MVPass5aqlUxkfVyeH73A1sfVQRaJhe0QLv1APRNCKYzqqFdP/a7xGRRegXkEuYFr3gfTqiJ7HY530XPOfK+SuIi9hx8OrSk0B7EjbMqr/iP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: default

