apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: default
spec:
  encryptedData:
    token: AgArFaNnO9SoZepoUyKNkBi199bKfK2TV6s0F77wuoDqF847lE6qXEPbsoif+tTrR10mHfNVE6IFy6n573I8ou4B0zQH8evst26dwHca91OpGcGfEETKgY7WiR5xzULbBmuQCVau7JVaF0C3eNS2DCPxdA5oV6zQiL0tCmgKpKzvEfdHg883N9ub//Yg4o0fmOW3KuXXklg/NnsJ993OJhDd0765lcyiibjPzY9a+3K3kbxNBFCput/Sy9uZIXmJNh6APSX0exb/e/FC+xO6Ry1C719nxzNYoByJQVYVQsbc7yWaY6Ssj8OG3Or+npPNdScFsLAkFWiDybWYLXpFGRtAjNyuDXRvfhCDc8oKp6Wfa7Tz6nZNcU2oCeXEzohQIIZz1m1aRuQsOcn9E4Iin9JcLNW9gDzAanaQvij1rYRrYQ8YTO/+l4a7LNSjXxm1tP2d3faoyY+QjDXlX2D+5GuJail7ic9ubTj6qfCWgpqrcWTbAIaRQABVJVbHi4TRdsgZm02PeRZ2gEpur8iNEHTVaUtAX4YaQAQusB3Kxn8kkRnvTvXsgAksoodYARXbQ9U/Pdw1d0vXCNxP4dQq+nLu62Rk/WIyY5qYoTuDYsQnO2zXeFwewLvtbov1J43OLbnP6EKomdvjFOGZZZZrKCMfx6U9Ojq/QTBN0puKWUSoOZF1DIYYlyMyfe0afWSa5+9TBgwHGm4KG8aGITAjx0Cx8AqxUgHiLwcf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: default

