apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: postgres-deployment
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-volume-storage
      volumes:
        - name: postgres-persistent-volume-storage
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim
