apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: postgres-persistent-volume-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
