apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: postgres-persistent-volume
  labels:
    app: postgres
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"
