alb:
  addr: 0.0.0.0
  ports:
    https: 443
  reconciliation: /reconcile
  tls:
    domains:
      opentracker.app:
        cert_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/opentracker.app/fullchain.pem
        key_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/opentracker.app/privkey.pem
      tags.opentracker.app:
        cert_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/tags.opentracker.app/fullchain.pem
        key_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/tags.opentracker.app/privkey.pem
      today.opentracker.app:
        cert_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/today.opentracker.app/fullchain.pem
        key_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/today.opentracker.app/privkey.pem
      uptime.opentracker.app:
        cert_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/uptime.opentracker.app/fullchain.pem
        key_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/uptime.opentracker.app/privkey.pem
      forkup.app:
        cert_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/forkup.app/fullchain.pem
        key_file:
          location: s3
          bucket: configuration-68f6c7
          key: f2/certificates/forkup.app/privkey.pem
  mtls:
    anchor:
      location: s3
      bucket: configuration-68f6c7
      key: f2/anchor.pem
    domains:
      - today.opentracker.app
      - uptime.opentracker.app

secrets:
  private_key:
    location: s3
    bucket: configuration-68f6c7
    key: f2/private.key

services:
  frontend:
    image: alexanderjackson/opentracker-frontend
    tag: 20240810-2043
    routes:
      - host: opentracker.app
        port: 80
    replicas: 1

  forkup-frontend:
    image: alexanderjackson/forkup-frontend
    tag: 20250915-2018
    routes:
      - host: forkup.app
        port: 80
    replicas: 1
    shutdown_mode: graceful

  tag-updater:
    image: alexanderjackson/tag-updater
    tag: 20250925-1606
    routes:
      - host: tags.opentracker.app
        port: 4025
    replicas: 1
    volumes:
      config:
        source:
          location: s3
          bucket: configuration-68f6c7
          key: tag-updater/config.yaml
        target: /app/config/tag-updater.yaml

  today:
    image: alexanderjackson/today
    tag: 20250925-1606
    routes:
      - host: today.opentracker.app
        port: 8000
    replicas: 1
    volumes:
      config:
        source:
          location: s3
          bucket: configuration-68f6c7
          key: today/config.yaml
        target: /app/config/today.yaml
    environment:
      FOO: bar
