apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: opentracker-frontend-deployment
  labels:
    app: opentracker-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opentracker-frontend
  template:
    metadata:
      labels:
        app: opentracker-frontend
    spec:
      containers:
        - name: opentracker-frontend
          image: alexanderjackson/opentracker-frontend:20220521-1424 # {"$imagepolicy": "flux-system:opentracker-frontend"}
