name: Deploy configuration to S3

on:
  push:
    branches: ["master"]
    paths:
    - "configuration/**"

jobs:
  deploy-config:
    name: Deploy configuration to S3
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./configuration
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Configuration
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.CONFIG_DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.CONFIG_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          source: ./config.yaml
          dest: s3://configuration-sfvz2s/f2/config.yaml
          aws_region: eu-west-1

      - name: Force Reconciliation
        run: curl https://opentracker.app/reconcile
